// <auto-generated />
using System;
using Electronic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Electronic.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250420091319_ProductMg")]
    partial class ProductMg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Electronic.Data.ProductCategoryMst", b =>
                {
                    b.Property<int>("C_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("C_Id"));

                    b.Property<DateTime>("C_CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("C_Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("C_IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("C_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("C_Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("C_Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ProductCategoryMsts");
                });

            modelBuilder.Entity("Electronic.Data.ProductMst", b =>
                {
                    b.Property<int>("P_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("P_Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("P_CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("P_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("P_IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("P_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("P_Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductMsts");
                });

            modelBuilder.Entity("Electronic.Data.ProductCategoryMst", b =>
                {
                    b.HasOne("Electronic.Data.ProductCategoryMst", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Electronic.Data.ProductMst", b =>
                {
                    b.HasOne("Electronic.Data.ProductCategoryMst", "Category")
                        .WithMany("ProductImages")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Electronic.Data.ProductCategoryMst", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
