// <auto-generated />
using System;
using Electronic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Electronic.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250321070025_ProductCategoryMsts_mg")]
    partial class ProductCategoryMsts_mg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Electronic.Data.ProductCategoryMst", b =>
                {
                    b.Property<int>("P_C_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("P_C_Id"));

                    b.Property<DateTime>("P_C_Entery_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("P_C_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P_C_Order")
                        .HasColumnType("int");

                    b.Property<bool>("P_C_Status")
                        .HasColumnType("bit");

                    b.HasKey("P_C_Id");

                    b.ToTable("ProductCategoryMsts");
                });

            modelBuilder.Entity("Electronic.Data.SubProductCategoryMst", b =>
                {
                    b.Property<int>("Sub_P_C_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sub_P_C_Id"));

                    b.Property<int>("Main_P_C_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Sub_P_C_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sub_P_C_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sub_P_C_Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sub_P_C_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sub_P_C_Oder")
                        .HasColumnType("int");

                    b.Property<bool>("Sub_P_C_Status")
                        .HasColumnType("bit");

                    b.HasKey("Sub_P_C_Id");

                    b.ToTable("SubProductCategoryMsts");
                });
#pragma warning restore 612, 618
        }
    }
}
